language: android

jdk: oraclejdk8

before_install:
 - chmod +x gradlew
 # newest Android NDK
   - if [ `uname -m` = x86_64]; then wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86_64.tar.bz2 -O ndk.tgz; else wget http://dl.google.com/android/ndk/android-ndk-r9c-linux-x86.tar.bz2 -O ndk.tgz; fi
   - tar -xf ndk.tgz
   - export ANDROID_NDK_HOME=`pwd`/android-ndk-r9c
   - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools:${ANDROID_NDK_HOME}

android:
  components:
    - build-tools-22.0.1
    - android-19
    - extra
    - ndk-bundle